### ISSUE TITLE
Shimmer Integration

### ISSUE THREAD

**Issue by adam-635** [buildcore-io/core#1001]
### Overview

This issue summarize all requirements for Shimmer / Testnet integration and breaks it down into individual tasks.

Shimmer (shimmer.network) is a new "staging" network that will launch late July. Also referred as Stardust. This Soonaverse implementation blocks its launch and its key component to successful Shimmer launch. We've been approached by IF to integrate Shimmer with Soonaverse. Numerous PR events are aligned with this. 

**Key integration:**
- NFT Minting / Burning
- NFT Transfer / Trading
- Token Minting
- Token Trading

There are other features we might choose to integrate (if time allows) but right now above are the most important one to get working

We've discover that Soonaverse L1 play is our key advantage and we will be focusing more and more on integrating Soonaverse with all Shimmer's features. We are also working actively with IF to introduce new output types to support our business logic (i.e. token trading) and make it more decentralized.

**Key documents to read:**
- Tokenization framework: https://github.com/lzpap/tips/blob/master/tips/TIP-0018/tip-0018.md
- Stardust deep dive: https://blog.shimmer.network/a-deep-dive-into-stardust/
- Stardust wiki: https://versioning.iota-community.org/introduction/develop/protocol/stardust_ledger
- Introduction video by key lead developers behind Stardust: https://www.icloud.com/iclouddrive/007WYE10FSIQktN-TPlrizpww#2022-06-02_15-03-37
- IOTA.js stardust branch: https://github.com/iotaledger/iota.js/tree/feat/stardust
- IOTA.js upcoming examples: https://github.com/iotaledger/iota.js/pull/881

We've started work on #773 which will allows us to run multiple networks on Soonaverse. We will easily add new networks by just adding it within config file. In our test environment (wen.soonaverse.com) we might choose to run both Shimmer / Testnet.

> Internal Testnet (alplhanet) is available since Jun 2. This what we can use ATM for internal testing. See https://hackmd.io/vWYdUmbKSZiWrsPNg0wQMA for all details.

**I HIGHLY recommend everyone to get familiar with Startdust / Shimmer.**

#### Delivery
We've got three key upcoming releases:
- [Release 0.12](https://app.zenhub.com/workspaces/public-master-61a51a3547b2090011dce2d2/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvNzg0NTQ)
- [Release 0.13](https://app.zenhub.com/workspaces/public-master-61a51a3547b2090011dce2d2/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvNzg0NTU)
- [Release 0.14](https://app.zenhub.com/workspaces/public-master-61a51a3547b2090011dce2d2/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvNzg0NTY)

**Release 0.12**
We're doing final clean-up and refactoring on both front-end and back-end to get ready for integration with Shimmer. This gives time to UX/UI team to finalize all screens and flows.

**Release 0.13**
Integration with Shimmer starts on both back-end and front-end. All hands are on Shimmer integration and everything else has less priority.

**Release 0.14** 
Fixing, cleaning up and stabilization period. We'll also have extensive testing done by a bigger group (IOTA Community).

### High-level Requirements
Soonaverse must support key functions:
- NFT
  - Ability to mint collection on the shimmer
  - Ability for individuals to mint their NFT on Shimmer (only after collection has been minted)
  - Ability to sent NFTs from Soonaverse to their own wallet
  - Ability to sent NFTs to Soonaverse from their own wallet (Gallery, make it available for re-sell/auction)
  - Ability to trade / re-sell NFTs
- Token
  - Ability to mint token on the shimmer
  - Ability for individuals to claim their Token on Shimmer (only after token has been minted)
  - Ability to trade tokens
- SMR / IOTA Trading
  - We want to support trading between networks. This will require 4-way fulfilment instead of 2-way fulfilment we have atm.

#### Ability to mint collection on the shimmer (existing)
- User will be able to go into collection and migrate it to Shimmer
- User will be required to send small amount of IOTAs to do so
- Once completed, all NFTs within that collection can be minted on Shimmer only

#### Ability to mint collection on the shimmer (new)
- User will create collection same way as before
- User has an option to mint the collection on the Shimmer anytime

#### User wants to mint NFT
- User selects NFT they own and mint the NFT on Shimmer (collection must be minted)
- User deposits 1Mi (they will receive it), NFT will be minted and sent to their IOTA address.
- NFT will disappear from Soonaverse (burn)

#### User wants NFT to show in Soonaverse gallery or make it available for sale/auction
- User will go into their profile and hit deposit NFT
- User deposits NFT by sending NFT from their wallet to Soonaverse
- User sees NFT in Soonaverse and can make it available for sale / auction
  - When set for auction / sale user can set expiry date after which it'll be automatically returned to their wallet and burned on Soonaverse

#### User purchase or wins NFT
- There are two options. This NFT can go into their gallery (stay within Soonaverse) or go straight into their wallet
  - If NFT has not been yet minted on Shimmer, it'll always just go to their Gallery (as it's now)
- By default it goes to their wallet although part of the bid user can change that and say it only goes to their gallery 

#### Token minting
- User goes into token and hits create token on Shimmer
- User pay deposit amount and token will be minted on Shimmer. Guardian that minted the token will control the token supply. All undistributed token will be deposited to the Guardian.
- User has an ability to define "vesting" period on each allocation bucket. If so, during minting we would separate those allocations and lock them on Shimmer until specified date.
- Distributed tokens will be held by Soonaverse for member's to claim.

#### User's token claiming
- Once token is minted users are able to claim their token.
- User goes to their profile and hit claim token. Pay small amount of IOTAs.
- User receive token to their wallet.

#### Token trading
- Once token is minted, asks transactions will work differently.
- User will have to send tokens to soonaverse to fulfill asks

#### @centercirclesolutions Hornet node customization TODO
- [ ] Provide link to your node so we can interact with it
- [ ] Start syncing milestone to soonaverse-test (Internal Testnet)
- [ ] Start syncing transactions details

### Limitations
- User will not be able to show NFTs under their Soonaverse profile if they want to hold NFT in their wallet
