### ISSUE TITLE
Add Angular Meta for SEO & link previews

### ISSUE THREAD

**Issue by adam-635** [buildcore-io/core#1404]
Let's implement basic SEO on all pages and make sure correct titles are set. This includes link previews.

Open graph preview links codes:
```
<meta property="og:title" content="">
<meta property="og:type" content="website">
<meta property="og:image" content="">
<meta property="og:url" content="">
```

SEO Tags:
![Screen Shot 2022-09-04 at 2.10.31 PM.png](https://images.zenhubusercontent.com/54f851af4f7a08fbb7f242c5/246971a7-a963-4bd9-9243-9b3031eac480)

Requirements:
- all fixed names must be translatable i18n
- dynamically refresh on route change
- title should be both og:title and page title
- og:type always website
- og:description should always equal to description. First 160 characters.

Pages to update:

- [ ]  
-- Title: 
-- Description: 
- [x]  Tokens - Favourites
-- Title: Tokens - Favourite | Soonaverse
-- Description: Your favourite token pairs.
-- og:image: Soonaverse placeholder
- [x]  Tokens - All tokens
-- Title: Tokens | Soonaverse
-- Description: All tokens on the platform.
-- og:image: Soonaverse placeholder
- [x]  Tokens - Trading Pairs
-- Title: Tokens - Trading Pairs | Soonaverse
-- Description: All trading pairs ready to be traded.
-- og:image: Soonaverse placeholder
- [x]  Tokens - Launchpad
-- Title: Tokens - Launchpad | Soonaverse
-- Description: All trading pairs ready to be traded.
-- og:image: Soonaverse placeholder
- [x]  Token Trading page
-- Title: Token - <SOON/MIOTA> | Soonaverse
-- Description: <token short description>
-- og:image: Token banner
- [x]  Token Details
-- Title: Token - <SOON Token> | Soonaverse
-- Description: <token short description>
-- og:image: Token banner
- [x]  New token
-- Title: New Token | Soonaverse
-- Description: Create your new token and launch on fee-less network today!
-- og:image: Soonaverse placeholder
- [x]  Marketplace - NFT
-- Title: NFTs - Marketplace | Soonaverse
-- Description: All amazing NFTs at one place.
-- og:image: Soonaverse placeholder
- [x]  Marketplace - Collection
-- Title: Collections - NFT | Soonaverse
-- Description: All amazing Collections at one place.
-- og:image: Soonaverse placeholder
- [x]  Collection Detail
-- Title: Collection - <name> | Soonaverse
-- Description: <collection description>
-- og:image: Collection banner
- [x]  NFT Detail
-- Title: NFT - <name> | Soonaverse
-- Description: <nft description>
-- og:image: NFT image
- [x]  Discovery Spaces
-- Title: Discover - Spaces | Soonaverse
-- Description: Discover all amazing DAO's on Soonaverse.
-- og:image: Soonaverse placeholder
- [x]  Discovery Awards
-- Title: Discover - Awards | Soonaverse
-- Description: Discover all badges you can get today.
-- og:image: Soonaverse placeholder
- [x]  Discovery Proposals
-- Title: Discover - Proposals | Soonaverse
-- Description: Discover things you can vote on today.
-- og:image: Soonaverse placeholder
- [x]  Discovery Members
-- Title: Discover - Members | Soonaverse
-- Description: Discover all members participating in Soonaverse.
-- og:image: Soonaverse placeholder
- [x]  Space Detail
-- Title: Space - <name> | Soonaverse
-- Description: <about>
-- og:image: Space banner
- [x]  Space Detail Awards
-- Title: Space - <name> - Awards | Soonaverse
-- og:image: Space banner
-- Description: Space's awards
- [x]  Space Detail Proposal
-- Title: Space - <name> - Proposals | Soonaverse
-- og:image: Space banner
-- Description: Space's proposals
- [x]  Space Detail Collections
-- Title: Space - <name> - Collections | Soonaverse
-- og:image: Space banner
-- Description: Space's collections
- [x]  Space Detail Members
-- Title: Space - <name> - Members | Soonaverse
-- Description: Space's members
-- og:image: Space banner
- [x]  New Space
-- Title: Space - New | Soonaverse
-- Description: Create your new DAO today.
-- og:image: Soonaverse placeholder
- [x]  New Award
-- Title: Award - New | Soonaverse
-- Description: Reward your community, give them badge!
-- og:image: Soonaverse placeholder
- [x]  Award Detail
-- Title: Award - <name> | Soonaverse
-- Description: <about>
-- og:image: Space banner
- [x]  Award Detail
-- Title: Award - <name> | Soonaverse
-- Description: <about>
-- og:image: Space banner
- [x]  Award Detail - Participants
-- Title: Award - <name> | Soonaverse
-- Description: See all participants within the award.
-- og:image: Space banner
- [x]  Proposal - New
-- Title: Proposal - New | Soonaverse
-- Description: Make key decision on fee-less protocol.
-- og:image: Soonaverse placeholder
- [x]  Proposal Detail
-- Title: Proposal - <name> | Soonaverse
-- Description: <about>
-- og:image: Space banner
- [x]  Proposal Detail - Participants
-- Title: Proposal - <name> - Participants | Soonaverse
-- Description: See all participants within the proposal.
-- og:image: Space banner
- [x]  Member Detail
-- Title: Member - <name> | Soonaverse
-- Description: <about>
-- og:image: Space banner
