### ISSUE TITLE
Fix our image repository

### ISSUE THREAD

**Issue by adam-635** [buildcore-io/core#1743]
This is a long overdue improvement on our infrastructure. Currently, we use combination of Google Storage, Resize Images extension by Firebase (https://extensions.dev/extensions/firebase/storage-resize-images), nft.storage & pinata. It's very messy.

**Limitations and issues:**
- we don't generate preview image for videos
- we convert images into different formats but don't store it within ipfs
- none of the images have prefix in our google storage and it destroy opportunity for us to cache
- we don't keep filename of the image in our database 
- we continue to use Pinata that's expensive and shit

**Action plan:**
- [x] generate CID before upload so we can immediately set IPFS information on NFT if possible!
- [x] switch over to web3.storage, use their upload and pinning to pin files. Move away from Pinata. We will need migration script to pin all existing images in database on web3.storage
- [x] move resize images Firebase extension into our trigger on storage so we can have tests for it and have it more custom
- [x] change folder structure to replicate ipfs structure. We store files with suffix (allows caching) and also store various other sizes. We also create video preview. Ideally we start uploading the same way into ipfs. This means once user uploads we move files to new folder. Ideally path in Firebase is only relative path to storage.
- [x] change all images in database to use images.soonaverse.com/<ipfs>/file.<extension> instead.

Any other suggestions will be much appreciated. See current configuration of "Resize Image" extension:

![Screenshot 2022-11-02 at 7.55.48 PM.png](https://images.zenhubusercontent.com/54f851af4f7a08fbb7f242c5/acdaeca8-4d76-42de-8420-f7b02c894c69)
