### ISSUE TITLE
Expand API to return Soonaverse addresses

### ISSUE THREAD

**Issue by adam-635** [buildcore-io/core#2260]
@boldizsar-unchained 

Can you please create an end point that returns all address for a network via the API? 

**TODO**
- [ ] Ideally we increase pagination to 1000. We limit to only return createdOn / address. Paginate by createdOn? In prod we got over 600k addresses so paginating by 100 records would be slow.
- [ ] filter by network should be mandatory
- [ ] let's not call the endpoint by  collection=_mnemonic. That would be very controversial. I would create a specific end point ie. public-addresses or something similar
- [ ] let's make sure we got tests to validate we never ever expose mnemonic field. This would be a huge security issue.

Background: https://explorer.shimmer.network/ team wants to visualized NFTs and wants to implement whitelist. They want to auto whitelist all collections that were minted by us. I proposed to them we can provide them list of Soonaverse addresses (instead of us submitting collection to their whitelist Github repo - slow)

This is part of the 0.18 because IF asked for it access asap as they want to release new explorer.
